site_name: AgnosPCB Documentation
theme:
  features:
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+tabs#navigation-tabs
    - navigation.tabs
    - navigation.tabs.sticky
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+tabs#anchor-tracking
    - navigation.tracking
    - navigation.instant
    - navigation.expand
  name: material
  palette:
    - scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Roboto
  favicon: assets/cropped-agnosPCB-favicon-192x192.webp
  logo: assets/cropped-agnosPCB-favicon-192x192.webp
extra_css:
  - stylesheets/agnos_colors.css
plugins:
  - search
   #  - Navigation
extra:
  version:
    provider: mike
nav:
  - Getting started:
    - Package content: 'getting_started/Package_content.md'
    - Unboxing guide: 'getting_started/Unboxing.md'
    - Connection guide: 'getting_started/Connection_guide.md'
    #- Account created: 'Account-created.md'
    #- Installation process: 'Installation_process.md'
  - How to use it:
    - Terminology: 'how_to/terminology.md'
    - User Interface: 'how_to/Screen-layout.md'
    - Inspection workflow: how_to/Inspection_workflow.md
    - Other functions:
      - Barcode reader: 'how_to/Barcode_reader.md'
      - Set exclusion area: 'how_to/Set_exclusion_area.md'
      - Set sensitivity: 'how_to/Set_sensitivity.md'
      - UUI to REFERENCE: 'how_to/UUI_to_REFERENCE.md'
      - Update your AOI computer: 'how_to/Update-your-AOI-computer.md'
      #- Auto processing: 'Auto_processing.md'
  - Help:
    - FAQ: 'help/FAQ.md'
    - Tips: 'help/Tips.md'
    #- General information: 'Products-and-services.md'
    # - Troubleshooting: 'Troubleshooting.md'
    
#  - privacy
copyright: Copyright &copy; 2023 - 2025 AgnosPCB
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true



