site_name: AgnosPCB Documentation
theme:
  features:
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+tabs#navigation-tabs
    - navigation.tabs
    - navigation.tabs.sticky
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+tabs#anchor-tracking
    - navigation.tracking
    - navigation.instant
  name: material
  palette:
    primary: custom
  font:
    text: Roboto
  favicon: assets/cropped-agnosPCB-favicon-192x192.webp
  logo: assets/cropped-agnosPCB-favicon-192x192.webp
extra_css:
  - stylesheets/agnos_colors.css
plugins:
  - search
   #  - Navigation
nav:
  - Getting started:
    - Account created: 'Account-created.md'
    - Package content: 'Package_content.md'
    - Assembly guide:
      - Platform assembly:  'Platform_assembly_guide.md'
      - Connecting ONLINE units: 'Connect_to_the_Nuc.md'
      - Connecting OFFLINE units: 'connecting_offline_units.md'
      #- Connect to the AgnosPCB Laptop: 'Connect_to_the_AgnosPCB_Laptop.md'
      - Connect to the camera: 'Connect-the-camera.md'
    - Installation process: 'Installation_process.md'
  - How to use it:
    - User guide: 'User_guide.md'
    - Inspection workflow: 'Inspection_workflow.md'
    - How to update your unit: 'updating_your_unit.md'
    - Main functions:
      - Screen layout:  'Screen-layout.md'
      - Barcode reader: 'Barcode_reader.md'
      - Generating a report: 'Generating _a_report.md'
      - Set exclusion area: 'Set_exclusion_area.md'
      - Set sensitivity: 'Set_sensitivity.md'
      - UUI to REFERENCE: 'UUI_to_REFERENCE.md'
      - Auto processing: 'Auto_processing.md'
  - Help:
    - General information: 'Products-and-services.md'
    - FAQ: 'FAQ.md'
    - Troubleshooting: 'Troubleshooting.md'
    - Update your AOI computer: 'Update-your-AOI-computer.md'
#  - privacy
copyright: Copyright &copy; 2023 - 2024 AgnosPCB
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html



