site_name: AgnosPCB Documentation
theme:
  features:
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+tabs#navigation-tabs
    - navigation.tabs
    - navigation.tabs.sticky
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+tabs#anchor-tracking
    - navigation.tracking
    - navigation.instant
    - navigation.expand
  name: material
  palette:
    - scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Roboto
  favicon: assets/cropped-agnosPCB-favicon-192x192-t.webp
  logo: assets/cropped-agnosPCB-favicon-192x192.webp
extra_css:
  - stylesheets/agnos_colors.css
plugins:
  - search
  #- Navigation
extra:
  version:
    provider: mike
nav:
  - Getting started:
    - Package content: 'getting_started/Package_content.md'
    - Unboxing guide: 'getting_started/Unboxing.md'
    - Connection guide: 'getting_started/Connection_guide.md'

  - How to use it:
    - Terminology: 'how_to/terminology.md'
    - User Interface: 'how_to/Screen-layout.md'
    - Inspection workflow: how_to/Inspection_workflow.md
    - Settings menu: how_to/Settings_menu.md
    - Other functions:
      - Barcode reader: 'how_to/Barcode_reader.md'
      - Exclusion area: 'how_to/Set_exclusion_area.md'
      - Sensitivity: 'how_to/Set_sensitivity.md'
      - UUI to REFERENCE: 'how_to/UUI_to_REFERENCE.md'
      - Network interface configuration: how_to/network_configuration.md
      - Workspace icons: how_to/Workspace_icons.md

  - Support:
    - Maintenance: maintenance/maintenance.md
    - Update software: maintenance/update_software.md
    - Troubleshooting: maintenance/Troubleshooting.md

  - Additional information:
    - FAQ: 'help/FAQ.md'
    - Tips: 'help/Tips.md'
     
    
#  - privacy
copyright: Copyright &copy; 2023 - 2025 AgnosPCB
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true



